apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-data-pvc
  namespace: api-relay-status
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qq-bot-data-pvc
  namespace: api-relay-status
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
