apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-pvc.yaml
  - 03-status-site.yaml
  - 04-qq-bot.yaml
images:
  - name: registry.example.com/api-relay-status
    newTag: "0.1.0"
